# Generated by Django 5.2.17 on 2026-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('credit_card', 'Credit/Debit Card'), ('upi', 'UPI'), ('net_bank', 'Net Banking')], default='cod', max_length=20),
        ),
    ]
